build

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,4 +1,28 @@
 #!/bin/bash
+# Make temporary dest dir, and clean up.
+dest=$(mktemp -d)
+echo $dest
+trap "{ rm -rf $dest; }" EXIT SIGINT SIGTERM
+
+# Commit to src branch if needed
+git checkout src
+if [[ `git status --porcelain` ]]; then
+    git add .
+    git commit -m "$1"
+fi
+
+# Build to temp directory
+jekyll build -d $dest
+
+# Checkout master, nuke everything
+git checkout master
+git rm -r .
+rm -rf *
+
+# Copy in built files
+cp -R $dest/* .
+
 git add .
-git commit -m "$1"
-git push
+git commit -m "build"
+
+# git push
